### ISSUE TITLE
[BUG] I cannot add the local version of Lite-XL to the managed list.

### ISSUE THREAD

**Issue by cvladan** [lite-xl/lite-xl-plugin-manager#12] opened 2023-03-04 14:58 UTC
This concerns Windows OS. My Lite-XL is installed using Scoop and it is the version with the basic plugins, also known as the "addons" package.

My first attempt to add my local Lite-XL installation to the managed list was unsuccessful. 

## Problem

I've tried the following:

```
lpm lite-xl add 2.1.1 c:\users\cvladan\scoop\apps\lite-xl-addons\current\
```

![image](https://user-images.githubusercontent.com/1913156/222908249-5ae3fcb3-f90f-4d91-8f8a-5092bfc16d0f.png)

It seems that LPM assumes, without justification, that the installation path ends with a folder called "lite-xl". 

## There is obviously a solution

I see that there are enough parameters that I could specify, but I am completely confused about what each one does, because there are too many of them. 

Please help!

## What is the correct command?

I want to add my local installation to the managed list.
My local installation is located in the folders:

```
1. Lite-XL install folder:   c:\users\cvladan\scoop\apps\lite-xl-addons\current\
2. Therefore binary file is: c:\users\cvladan\scoop\apps\lite-xl-addons\current\lite-xl.exe
3. Data aka config folder:   c:\users\cvladan\.config\lite-xl
4. There is a plugin folder: c:\users\cvladan\.config\lite-xl\plugins
5. And LPM related:          c:\users\cvladan\.config\lite-xl\lpm\repos
```
And there are so many switches.

```
  --userdir=directory      Sets the lite-xl userdir manually ( that id probably my no 3. )
  --cachedir=directory     Sets the directory to store all repositories ( probably 5. but I guess I don't need it )
  --tmpdir=directory       During install, sets the staging area ( no important )
  --datadir=directory      Sets the data directory where core addons are located ( is this 3. or 4. )
  --binary=path            Sets the lite-xl binary path for the system lite-xl ( this is probably 2. )
```

What should I type to "bypass" the error from the beginning and specify each folder separately?

Thank you!

**Comment by adamharrison** [comment] 2023-03-05 21:14
So, it's not that it's looking for a folder called `lite-xl`, it's looking for the binary `lite-xl`. As it stands, it looks for two things; the binary, under `lite-xl` under that path, and the data directory under that path `data`. 

So there's two issues here; one, it's not looking for the `lite-xl.exe`; only `lite-xl`. So I'll make sure it gets the right extension. The second is, that that command doesn't pay attention to `--binary` or `--datadir`. I'll make it so it does.

Also, a note about the switches: The data folder isn't the `.config\lite-xl` one, that's your `userdir`. `datadir` and `userdir` can be the same folder, but it's be very unusual. Usually the `datadir` is either immediately  next to the executable, or on linux, in `/usr/share`.  So you would need to find the `datadir`. So, by default:

```
  --userdir        ~/.config/lite-xl
  --cachedir     ~/.config/lite-xl/lpm
  --tmpdir        ~/.config/lite-xl/lpm/tmp
  --datadir       <lite-xl-install-path>/data
  --binary         <lite-xl-install-path>/lite-xl.exe
```

So let me fix up some of the lpm `lite-xl` commands (I haven't tested them very heavily) to use these options appropriately, and to pay attention to the right executable extensions on windows, and I'll get back to you.

**Comment by adamharrison** [comment] 2023-03-14 21:37
OK; I think I've got it. Testing now.

**Comment by adamharrison** [comment] 2023-03-14 21:49
OK! So with the latest release, the binary, and datadir flags should work; they should also be inferred if you pass the folder that `lite-xl.exe` and `data` are in.

**Comment by adamharrison** [comment] 2023-03-24 14:43
Hey, I'm going to close this; feel free to reopen if the issue is still occurring.

**Closed by adamharrison** 2023-03-24 14:43 UTC
